### ISSUE TITLE
Chat doesn't work online

### ISSUE THREAD

**Issue by roccopung** [roccopung/export-radio#9]
In the meantime that we are waiting for Max reply, today I have tried to put the website online on a free hosting platform, to simulate how it would be when we go online in a week. For some reason, the chat still doesn't work, and I can't log in to social media to join the conversation. Do you eventually have any idea of why this happens?

In case that can help, you can find the website here [http://roccomaster.altervista.org/](http://roccomaster.altervista.org/)
You can access the Panel here with [https://en.altervista.org/](https://en.altervista.org/).

**Comment by awesomephant** [comment]
Don't post credentials here, this is a public website. I removed them from your comment for you.

The chat works fine for me (including logging in via Twitter) once I disable my Adblocker and tracking blocker in Firefox. I suspect this is an issue on their side, I don't know how well-maintained that project is. Is there a reason you're not embedding the Twitch chat? That one works fine in my experience.

**Comment by roccopung** [comment]
Thanks for removing it, I know it is public but just didn't consider it an issue. Very bad idea anyway!

The reason was that you would need a Twitch account to log in to the chat and participate, while here was easier to join in... However, it looks like it creates some problems, and even if I disable Adblocker and tracking in Chrome, it doesn't work. I know you used it on another website, did it create any problem there?

**Comment by awesomephant** [comment]
I made a [test case here](https://maxkoehler.com/test/) which seems to work in Chrome, I suspect because my site uses https. You could set that up for the Export Radio site and probably improve your chances, but honestly the component just seems a little dead to me. 

Might make your life easier to go back to Twitch. The fact that it forces you to log in isn't that bad in my opinion - it's actually a safety feature. If people have to log in through Twitch, they can be banned by Twitch for spam, abuse, illegal content and so on. This is why we used it on [this site](https://www.loveactually.works/), and it worked just fine.

**Comment by roccopung** [comment]
Ooh so that wasn't tlk.io that you used! Ok then, what you say makes total
sense to me and I will forward the information. I stop bothering you for
today.

Thank you as always and have a nice evening!

Il gio 7 gen 2021, 21:38 Max Kohler <notifications@github.com> ha scritto:

**Comment by roccopung** [comment]
Changed to Twitch. Just much better. I close this issue.
